import { DocsPage } from './types';

export interface DocSection {
  id: 'start-here' | 'core-concepts' | 'instructions' | 'security';
  title: string;
  pages: { slug: string; title: string }[];
}

export const DOC_SECTIONS: DocSection[] = [
  {
    id: 'start-here',
    title: 'Start Here',
    pages: [
      { slug: 'index', title: 'Introduction' },
      { slug: 'quick-start', title: 'Quick Start' },
      { slug: 'architecture', title: 'Architecture' },
    ],
  },
  {
    id: 'core-concepts',
    title: 'Core Concepts',
    pages: [
      { slug: 'continuous-vs-twilight', title: 'Continuous vs. Twilight' },
      { slug: 'uniform-price-clearing', title: 'Uniform Price Clearing' },
      { slug: 'confidence-bands', title: 'Confidence Bands' },
    ],
  },
  {
    id: 'instructions',
    title: 'Instructions',
    pages: [
      { slug: 'initialize-market', title: 'initialize_market' },
      { slug: 'evaluate-market-mode', title: 'evaluate_market_mode' },
      { slug: 'place-batch-order', title: 'place_batch_order' },
      { slug: 'cancel-batch-order', title: 'cancel_batch_order' },
      { slug: 'settle-batch-auction', title: 'settle_batch_auction' },
      { slug: 'claim-order-proceeds', title: 'claim_order_proceeds' },
    ],
  },
  {
    id: 'security',
    title: 'Security',
    pages: [
      { slug: 'invariants', title: 'Invariants & Threat Model' },
      { slug: 'known-limitations', title: 'Known Limitations' },
    ],
  },
];

export const DOC_PAGES: Record<string, DocsPage> = {
  'start-here/index': {
    slug: 'index',
    section: 'start-here',
    sectionTitle: 'Start Here',
    title: 'Introduction to TwilightBook',
    description: 'A 24/7 tokenized-equity venue on Solana switching between continuous swaps and discrete uniform-price batch auctions.',
    headings: [
      { id: 'overview', title: 'Overview', level: 2 },
      { id: 'problem', title: 'The TradFi Off-Hours Problem', level: 2 },
      { id: 'solution', title: 'The Twilight Solution', level: 2 },
      { id: 'key-features', title: 'Key Features', level: 2 },
    ],
    prev: undefined,
    next: { title: 'Quick Start', href: '/docs/start-here/quick-start' },
  },
  'start-here/quick-start': {
    slug: 'quick-start',
    section: 'start-here',
    sectionTitle: 'Start Here',
    title: 'Quick Start Guide',
    description: 'Clone, build, test, and deploy TwilightBook on Solana localnet or devnet.',
    headings: [
      { id: 'prerequisites', title: 'Prerequisites', level: 2 },
      { id: 'clone-and-build', title: 'Clone & Build', level: 2 },
      { id: 'running-bankrun-tests', title: 'Running Bankrun Tests', level: 2 },
      { id: 'devnet-deployment', title: 'Devnet Deployment', level: 2 },
    ],
    prev: { title: 'Introduction', href: '/docs/start-here/index' },
    next: { title: 'Architecture', href: '/docs/start-here/architecture' },
  },
  'start-here/architecture': {
    slug: 'architecture',
    section: 'start-here',
    sectionTitle: 'Start Here',
    title: 'System Architecture',
    description: 'The Pyth circuit evaluator sitting between continuous swaps and discrete batch auction ring buffer.',
    headings: [
      { id: 'circuit-evaluator', title: 'Pyth Circuit Evaluator', level: 2 },
      { id: 'state-machine', title: 'Market State Machine', level: 2 },
      { id: 'account-model', title: 'Account Model & PDAs', level: 2 },
    ],
    prev: { title: 'Quick Start', href: '/docs/start-here/quick-start' },
    next: { title: 'Continuous vs. Twilight', href: '/docs/core-concepts/continuous-vs-twilight' },
  },
  'core-concepts/continuous-vs-twilight': {
    slug: 'continuous-vs-twilight',
    section: 'core-concepts',
    sectionTitle: 'Core Concepts',
    title: 'Continuous vs. Twilight Mode',
    description: 'Why the mode switch exists: defending against adverse selection during TradFi market closes.',
    headings: [
      { id: 'the-135-hour-window', title: 'The 135-Hour Window', level: 2 },
      { id: 'adverse-selection', title: 'Adverse Selection in AMMs', level: 2 },
      { id: 'dynamic-mode-switch', title: 'The Dynamic Mode Switch', level: 2 },
    ],
    prev: { title: 'Architecture', href: '/docs/start-here/architecture' },
    next: { title: 'Uniform Price Clearing', href: '/docs/core-concepts/uniform-price-clearing' },
  },
  'core-concepts/uniform-price-clearing': {
    slug: 'uniform-price-clearing',
    section: 'core-concepts',
    sectionTitle: 'Core Concepts',
    title: 'Uniform Price Clearing (P* / Q*)',
    description: 'Discrete batch auctions execute all matched volume at a single uniform clearing price.',
    headings: [
      { id: 'uniform-pricing-principle', title: 'The Uniform Price Principle', level: 2 },
      { id: 'worked-example', title: 'Concrete Worked Example', level: 2 },
      { id: 'tie-break-rule', title: 'Tie-Break Rule', level: 2 },
      { id: 'price-improvement-refund', title: 'Buyer Price-Improvement Refund', level: 2 },
    ],
    prev: { title: 'Continuous vs. Twilight', href: '/docs/core-concepts/continuous-vs-twilight' },
    next: { title: 'Confidence Bands', href: '/docs/core-concepts/confidence-bands' },
  },
  'core-concepts/confidence-bands': {
    slug: 'confidence-bands',
    section: 'core-concepts',
    sectionTitle: 'Core Concepts',
    title: 'Pyth Confidence Bands',
    description: 'How bounded trade envelopes stop toxic flow and front-running.',
    headings: [
      { id: 'formula', title: 'Mathematical Formulation', level: 2 },
      { id: 'client-validation', title: 'Client-Side vs On-Chain Enforcement', level: 2 },
      { id: 'shock-behavior', title: 'Behavior Under Volatility Spikes', level: 2 },
    ],
    prev: { title: 'Uniform Price Clearing', href: '/docs/core-concepts/uniform-price-clearing' },
    next: { title: 'initialize_market', href: '/docs/instructions/initialize-market' },
  },
  'instructions/initialize-market': {
    slug: 'initialize-market',
    section: 'instructions',
    sectionTitle: 'Instructions',
    title: 'initialize_market',
    description: 'One-time instruction to initialize a new tokenized equity market pair and its vaults.',
    headings: [
      { id: 'accounts', title: 'Accounts', level: 2 },
      { id: 'arguments', title: 'Arguments', level: 2 },
      { id: 'errors', title: 'Errors', level: 2 },
      { id: 'example', title: 'TypeScript Example', level: 2 },
    ],
    prev: { title: 'Confidence Bands', href: '/docs/core-concepts/confidence-bands' },
    next: { title: 'evaluate_market_mode', href: '/docs/instructions/evaluate-market-mode' },
  },
  'instructions/evaluate-market-mode': {
    slug: 'evaluate-market-mode',
    section: 'instructions',
    sectionTitle: 'Instructions',
    title: 'evaluate_market_mode',
    description: 'Permissionless circuit evaluator instruction that checks Pyth oracle status and flips market mode.',
    headings: [
      { id: 'accounts', title: 'Accounts', level: 2 },
      { id: 'arguments', title: 'Arguments', level: 2 },
      { id: 'errors', title: 'Errors', level: 2 },
      { id: 'example', title: 'TypeScript Example', level: 2 },
    ],
    prev: { title: 'initialize_market', href: '/docs/instructions/initialize-market' },
    next: { title: 'place_batch_order', href: '/docs/instructions/place-batch-order' },
  },
  'instructions/place-batch-order': {
    slug: 'place-batch-order',
    section: 'instructions',
    sectionTitle: 'Instructions',
    title: 'place_batch_order',
    description: 'Places a limit bid or ask into the active epoch batch ring buffer, escrowing tokens.',
    headings: [
      { id: 'accounts', title: 'Accounts', level: 2 },
      { id: 'arguments', title: 'Arguments', level: 2 },
      { id: 'errors', title: 'Errors', level: 2 },
      { id: 'example', title: 'TypeScript Example', level: 2 },
    ],
    prev: { title: 'evaluate_market_mode', href: '/docs/instructions/evaluate-market-mode' },
    next: { title: 'cancel_batch_order', href: '/docs/instructions/cancel-batch-order' },
  },
  'instructions/cancel-batch-order': {
    slug: 'cancel-batch-order',
    section: 'instructions',
    sectionTitle: 'Instructions',
    title: 'cancel_batch_order',
    description: 'Cancels an unfilled batch order and returns escrowed tokens, subject to the anti-sniping freeze window.',
    headings: [
      { id: 'accounts', title: 'Accounts', level: 2 },
      { id: 'arguments', title: 'Arguments', level: 2 },
      { id: 'errors', title: 'Errors', level: 2 },
      { id: 'example', title: 'TypeScript Example', level: 2 },
    ],
    prev: { title: 'place_batch_order', href: '/docs/instructions/place-batch-order' },
    next: { title: 'settle_batch_auction', href: '/docs/instructions/settle-batch-auction' },
  },
  'instructions/settle-batch-auction': {
    slug: 'settle-batch-auction',
    section: 'instructions',
    sectionTitle: 'Instructions',
    title: 'settle_batch_auction',
    description: 'Permissionless keeper action to clear the batch auction once the epoch ends and advance to the next epoch.',
    headings: [
      { id: 'accounts', title: 'Accounts', level: 2 },
      { id: 'arguments', title: 'Arguments', level: 2 },
      { id: 'errors', title: 'Errors', level: 2 },
      { id: 'example', title: 'TypeScript Example', level: 2 },
    ],
    prev: { title: 'cancel_batch_order', href: '/docs/instructions/cancel-batch-order' },
    next: { title: 'claim_order_proceeds', href: '/docs/instructions/claim-order-proceeds' },
  },
  'instructions/claim-order-proceeds': {
    slug: 'claim-order-proceeds',
    section: 'instructions',
    sectionTitle: 'Instructions',
    title: 'claim_order_proceeds',
    description: 'Claims bought tokens, sale proceeds, unfilled returns, and price-improvement refunds for a settled order.',
    headings: [
      { id: 'accounts', title: 'Accounts', level: 2 },
      { id: 'arguments', title: 'Arguments', level: 2 },
      { id: 'errors', title: 'Errors', level: 2 },
      { id: 'example', title: 'TypeScript Example', level: 2 },
    ],
    prev: { title: 'settle_batch_auction', href: '/docs/instructions/settle-batch-auction' },
    next: { title: 'Invariants & Threat Model', href: '/docs/security/invariants' },
  },
  'security/invariants': {
    slug: 'invariants',
    section: 'security',
    sectionTitle: 'Security',
    title: 'Invariants & STRIDE Threat Model',
    description: 'The mathematical invariants (INV-01 through INV-05) and mitigations against front-running and oracle tampering.',
    headings: [
      { id: 'core-invariants', title: 'Core Protocol Invariants', level: 2 },
      { id: 'stride-threat-model', title: 'STRIDE Threat Analysis', level: 2 },
      { id: 'reentrancy-escrow', title: 'Escrow Solvency Guarantee', level: 2 },
    ],
    prev: { title: 'claim_order_proceeds', href: '/docs/instructions/claim-order-proceeds' },
    next: { title: 'Known Limitations', href: '/docs/security/known-limitations' },
  },
  'security/known-limitations': {
    slug: 'known-limitations',
    section: 'security',
    sectionTitle: 'Security',
    title: 'Known Limitations',
    description: 'Documented protocol trade-offs, pro-rata rounding dust bounds, and mock oracle scope.',
    headings: [
      { id: 'pro-rata-dust', title: 'Pro-Rata Rounding Dust', level: 2 },
      { id: 'mock-oracle-scope', title: 'Demo-Only Mock Oracle', level: 2 },
      { id: 'ring-buffer-capacity', title: 'Batch Buffer Capacity (32 Orders)', level: 2 },
    ],
    prev: { title: 'Invariants & Threat Model', href: '/docs/security/invariants' },
    next: undefined,
  },
};
